version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:A4eTemeiUfMTNyPr13s3aN7Jk7HFYpQTcmybsIUD5sg=
      APP_DEBUG: "true"
      APP_TIMEZONE: UTC
      APP_URL: http://localhost
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: postgres
      DB_USERNAME: baha
      DB_PASSWORD: baha
    depends_on:
      - db

  web:
    image: nginx:latest
    container_name: nginx_web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: baha
      POSTGRES_PASSWORD: baha
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg_data:
